import "~/styles/globals.css";
import "@uploadthing/react/styles.css";
import { UploadButton } from "../utils/uploadthing";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Inter } from "next/font/google";
import Link from "next/link";
import { Themeroviders } from "./Themeproviders";
import { ThemeChange } from "components/theme";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <Themeroviders>
          <body className={`font-sans ${inter.variable}`}>
            <nav className="flex items-center justify-between border-b bg-gray-900 p-4 text-white">
              <div className="relative flex items-center gap-x-3">
                <Link href="/" className="text-xl font-semibold  ">
                  Gallery
                </Link>

                <Link
                  href="/upload"
                  className="text-xl font-semibold text-white "
                >
                  Upload
                </Link>
                <div className="">
                  <ThemeChange />
                </div>
              </div>
              <div>
                <SignedOut>
                  <SignInButton />
                </SignedOut>
                <SignedIn>
                  {/* <UploadButton endpoint="imageUploader" /> */}
                  <UserButton />
                </SignedIn>
              </div>
            </nav>
            {children}
          </body>
        </Themeroviders>
      </html>
    </ClerkProvider>
  );
}
