import "~/styles/globals.css";

import { Inter } from "next/font/google";
import Link from "next/link";
import { Providers } from "./providers";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});


export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export  default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en" suppressHydrationWarning>
      
      <body className={`font-sans ${inter.variable}`}>
        <nav className="flex items-center justify-between border-b bg-gray-900 p-4 text-white">
          <Link href="/" className="text-xl font-semibold  ">
            Gallery
          </Link>
          <div>
            <Link href="/" className="text-xl font-semibold  ">
            Sign in
           </Link>
        
          </div>
        </nav>
        <Providers>
        {children}
        </Providers>
      </body>
      
    </html>
  );
}
